// <auto-generated />
using System;
using IntelliMedi.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntelliMedi.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702155539_DisponibilitaMedicoDateOnly")]
    partial class DisponibilitaMedicoDateOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("IntelliMedi.API.Models.Amministratore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Amministratori");
                });

            modelBuilder.Entity("IntelliMedi.API.Models.Appuntamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PazienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipologiaVisitaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PazienteId");

                    b.HasIndex("TipologiaVisitaId");

                    b.ToTable("Appuntamenti");
                });

            modelBuilder.Entity("IntelliMedi.API.Models.DisponibilitaMedico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("Giorno")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("OraFine")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("OraInizio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId");

                    b.ToTable("DisponibilitaMedici");
                });

            modelBuilder.Entity("IntelliMedi.API.Models.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceFiscale")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascita")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sesso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Medici");
                });

            modelBuilder.Entity("IntelliMedi.API.Models.Paziente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceFiscale")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascita")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sesso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pazienti");
                });

            modelBuilder.Entity("IntelliMedi.API.Models.Recensione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descrizione")
                        .HasColumnType("TEXT");

                    b.Property<int>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PazienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Voto")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PazienteId");

                    b.ToTable("Recensioni");
                });

            modelBuilder.Entity("IntelliMedi.API.Models.TipologiaVisita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TipologieVisita");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descrizione = "Visita sportiva"
                        },
                        new
                        {
                            Id = 2,
                            Descrizione = "Ortopedia"
                        },
                        new
                        {
                            Id = 3,
                            Descrizione = "Nutrizione"
                        },
                        new
                        {
                            Id = 4,
                            Descrizione = "Cardiologia"
                        },
                        new
                        {
                            Id = 5,
                            Descrizione = "Psicologia"
                        },
                        new
                        {
                            Id = 6,
                            Descrizione = "Fisioterapia"
                        },
                        new
                        {
                            Id = 7,
                            Descrizione = "Holter cardiaco"
                        },
                        new
                        {
                            Id = 8,
                            Descrizione = "Onde d'urto"
                        });
                });

            modelBuilder.Entity("MedicoTipologiaVisita", b =>
                {
                    b.Property<int>("MediciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipologiaVisiteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediciId", "TipologiaVisiteId");

                    b.HasIndex("TipologiaVisiteId");

                    b.ToTable("MedicoTipologiaVisita");
                });

            modelBuilder.Entity("IntelliMedi.API.Models.Appuntamento", b =>
                {
                    b.HasOne("IntelliMedi.API.Models.Medico", "Medico")
                        .WithMany("Appuntamenti")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntelliMedi.API.Models.Paziente", "Paziente")
                        .WithMany("Appuntamenti")
                        .HasForeignKey("PazienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntelliMedi.API.Models.TipologiaVisita", "TipologiaVisita")
                        .WithMany()
                        .HasForeignKey("TipologiaVisitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paziente");

                    b.Navigation("TipologiaVisita");
                });

            modelBuilder.Entity("IntelliMedi.API.Models.DisponibilitaMedico", b =>
                {
                    b.HasOne("IntelliMedi.API.Models.Medico", "Medico")
                        .WithMany("Disponibilita")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("IntelliMedi.API.Models.Recensione", b =>
                {
                    b.HasOne("IntelliMedi.API.Models.Medico", "Medico")
                        .WithMany("Recensioni")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntelliMedi.API.Models.Paziente", "Paziente")
                        .WithMany("Recensioni")
                        .HasForeignKey("PazienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paziente");
                });

            modelBuilder.Entity("MedicoTipologiaVisita", b =>
                {
                    b.HasOne("IntelliMedi.API.Models.Medico", null)
                        .WithMany()
                        .HasForeignKey("MediciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntelliMedi.API.Models.TipologiaVisita", null)
                        .WithMany()
                        .HasForeignKey("TipologiaVisiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntelliMedi.API.Models.Medico", b =>
                {
                    b.Navigation("Appuntamenti");

                    b.Navigation("Disponibilita");

                    b.Navigation("Recensioni");
                });

            modelBuilder.Entity("IntelliMedi.API.Models.Paziente", b =>
                {
                    b.Navigation("Appuntamenti");

                    b.Navigation("Recensioni");
                });
#pragma warning restore 612, 618
        }
    }
}
